name: adv_sandeep
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.0.0
  path_provider: ^2.0.11
  open_file: ^3.2.1
  flutter_typeahead: ^4.0.0
  http: ^1.3.0
  shared_preferences: ^2.5.2
  pdf: ^3.11.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
